# -*- coding: utf-8 -*-
"""pipiproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PJBVP_Y20YpQf8GYBk1il0qR-CyObF-6
"""

import pandas as pd

datos = pd.read_csv('listado.csv')

df1

df1 = pd.DataFrame(datos)

viejos = pd.DataFrame(datos)

datos_filtrados = viejos['DNI']<45000000

viejos[datos_filtrados]



viejos[['Apellido y Nombre','DNI']]

datos_filtrados['Número de Alumno' , 'Apellido y Nombre' , 'DNI']

nuevo=pd.DataFrame(datos)

nuevo

nuevo[["DNI", "Apellido y Nombre"]]

nuevo.head(10)

nuevo.tail(15)